version: '3'
services:
  dobby:
    container_name: dobby
    build:
      context: .
    volumes:
      - ./exchange/:/dobby/exchange

    restart: unless-stopped
  wildfly:
    container_name: wildfly
    build:
      context: ./wildfly
    ports:
      - '8080:8080'
      - '9990:9990'
    environment:
      - WILDFLY_PASSWORD=password
    volumes:
      - "./exchange/:/tmp/exchange"
      #- "./deployments/:/opt/jboss/wildfly/standalone/deployments"
      #- "./modules/system/layers/base/com/microsoft/sqlserver/main/:/opt/jboss/wildfly/modules/system/layers/base/com/microsoft/sqlserver/main/"
      #- "./standalone/configuration/standalone.xml/:/opt/jboss/wildfly/standalone/configuration/standalone.xml"

  keycloack:
    container_name: keycloack
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - '8090:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin