version: '3'
services:
  dobby:
    container_name: dobby
    build:
      context: .
    volumes:
      - ./exchange/:/dobby/exchange

    restart: unless-stopped
  wildfly:
    container_name: wildfly
    build:
      context: ./wildfly
    ports:
      - '8080:8080'
      - '9990:9990'
    environment:
      - WILDFLY_PASSWORD=password
    volumes:
      - "./exchange/:/tmp/exchange"
      #- "./deployments/:/opt/jboss/wildfly/standalone/deployments"
      #- "./modules/system/layers/base/com/microsoft/sqlserver/main/:/opt/jboss/wildfly/modules/system/layers/base/com/microsoft/sqlserver/main/"
      #- "./standalone/configuration/standalone.xml/:/opt/jboss/wildfly/standalone/configuration/standalone.xml"

  keycloack:
    container_name: keycloack
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - '8090:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  sqlserver:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "P@ssword"
      ACCEPT_EULA: "Y"
    ports:
      - "14033:1433"
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mydb-db:/var/lib/mysql

volumes:
  mydb-db:
