version: "3"

services:
  wildfly:
    #image: 'jboss/wildfly'
    build: .
    ports:
      - '8080:8080'
      - '9990:9990'
    environment:
      - WILDFLY_PASSWORD=password
    volumes:
      - "./deployments/:/opt/jboss/wildfly/standalone/deployments"
      #- "./modules/system/layers/base/com/microsoft/sqlserver/main/:/opt/jboss/wildfly/modules/system/layers/base/com/microsoft/sqlserver/main/"
      #- "./standalone/configuration/standalone.xml/:/opt/jboss/wildfly/standalone/configuration/standalone.xml"


      

